lib/remote_retro_web/router.ex
defmodule RemoteRetroWeb.Router do
  use RemoteRetroWeb, :router
  use Honeybadger.Plug

  import Phoenix.LiveDashboard.Router

  alias RemoteRetroWeb.{PageController, AuthController, Plugs}

  @live_dashboard_repos Application.compile_env(:remote_retro, :live_dashboard_repos)
  @auth_controller Application.compile_env(:remote_retro, :auth_controller)

  if Application.compile_env(:remote_retro, :env) == :dev do
    forward("/sent_emails", Bamboo.SentEmailViewerPlug)
  end

  pipeline :authentication_required do
    plug(Plugs.RedirectUnauthenticated)
  end

  pipeline :forbid_non_striders do
    plug(Plugs.SetCurrentUserOnAssignsIfAuthenticated)
    plug(Plugs.ForbidNonStriders)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug PlugMinifyHtml
  end

  scope "/" do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/faq", PageController, :faq)
    get("/privacy", PageController, :privacy)
    get("/auth/google", AuthController, :index)
    get("/auth/google/callback", @auth_controller, :callback)
    get("/logout", AuthController, :logout)
  end

  scope "/retros", RemoteRetroWeb do
    pipe_through([:browser, :authentication_required])

    resources("/", RetroController, only: [:index, :create, :show])
  end

  scope "/admin" do
    pipe_through [:browser, :authentication_required, :forbid_non_striders]
    live_dashboard "/dashboard", metrics: RemoteRetroWeb.Telemetry, ecto_repos: @live_dashboard_repos
  end
end

web/router.ex
defmodule RemoteRetro.Router do
  use RemoteRetro.Web, :router
  use Honeybadger.Plug

  if Application.get_env(:remote_retro, :env) == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  pipeline :authentication_required do
    plug RedirectUnauthenticated
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug RedirectHerokuappTrafficToCustomDomain
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", RemoteRetro do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/faq", PageController, :faq
    get "/auth/google", AuthController, :index
    get "/auth/google/callback", AuthController, :callback
  end

  scope "/retros", RemoteRetro do
    pipe_through [:browser, :authentication_required]

    resources "/", RetroController, only: [:index, :create, :show]
  end
end

lib/remote_retro/data/retro.ex
defmodule RemoteRetro.Data.Retro do
  use RemoteRetroWeb, :model
  alias RemoteRetro.Data.{Idea, Participation}

  @primary_key {:id, :binary_id, autogenerate: true}

  @required_fields [:facilitator_id]

  @derive {Jason.Encoder, except: [:__meta__, :participations, :action_items]}
  schema "retros" do
    has_many(:participations, Participation)

    has_many(:ideas, Idea)
    has_many(:action_items, Idea, where: [category: "action-item"])

    has_many(:votes, through: [:ideas, :votes])
    has_many(:users, through: [:participations, :user])

    field(:stage, :string, read_after_writes: true)
    field(:facilitator_id, :id, read_after_writes: true)

    timestamps(type: :utc_datetime_usec)
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:stage, :facilitator_id])
    |> validate_required(@required_fields)
    |> validate_inclusion(:stage, [
      "lobby",
      "prime-directive",
      "idea-generation",
      "grouping",
      "voting",
      "action-items",
      "closed"
    ])
  end
end

web/models/retro.ex
defmodule RemoteRetro.Retro do
  use RemoteRetro.Web, :model

  @primary_key {:id, :binary_id, autogenerate: true}

  @required_fields [:facilitator_id]

  @derive {Poison.Encoder, except: [:__meta__, :participations]}
  schema "retros" do
    has_many :participations, RemoteRetro.Participation
    has_many :ideas, RemoteRetro.Idea
    has_many :votes, through: [:ideas, :votes]
    has_many :users, through: [:participations, :user]

    field :stage, :string, read_after_writes: true
    field :facilitator_id, :id, read_after_writes: true

    timestamps(type: :utc_datetime)
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:stage, :facilitator_id])
    |> validate_required(@required_fields)
    |> validate_inclusion(:stage, ["lobby", "prime-directive", "idea-generation", "voting", "action-items", "closed"])
  end
end

lib/remote_retro_web/controllers/retro_controller.ex
defmodule RemoteRetroWeb.RetroController do
  use RemoteRetroWeb, :controller
  alias RemoteRetro.{Retro, Participation, Idea}
  alias RemoteRetroWeb.ErrorView
  alias Phoenix.Token

  plug :verify_retro_id_param_is_uuid when action in [:show]
  plug RemoteRetroWeb.Plugs.SetCurrentUserOnAssignsIfAuthenticated when action in [:show]

  def index(conn, _params) do
    current_user_id = get_session(conn, "current_user_id")
    current_user_given_name = get_session(conn, "current_user_given_name")

    render(conn, "index.html", %{
      current_user_given_name: current_user_given_name,
      retros: recent_retros_with_action_items_preloaded(current_user_id),
      title: "Dashboard | RemoteRetro.org"
    })
  end

  def show(conn, params) do
    %{current_user: current_user} = conn.assigns

    # TODO: async retrieve the user record and assign the participation, as we already have the current user's id on the session
    soft_insert_participation_record!(current_user.id, params["id"])

    render(conn, "show.html", %{
      body_class: "retro-show-page",
      user_token: Token.sign(conn, "user", current_user),
      retro_uuid: params["id"],
      include_js: true
    })
  end

  def create(conn, params) do
    current_user_id = get_session(conn, "current_user_id")

    {:ok, retro} =
      %Retro{facilitator_id: current_user_id, format: params["format"]}
      |> Retro.changeset()
      |> Repo.insert()

    redirect(conn, to: "/retros/" <> retro.id)
  end

  def verify_retro_id_param_is_uuid(conn, _options) do
    %{"id" => id} = conn.path_params

    case Ecto.UUID.cast(id) do
      {:ok, _} ->
        conn

      _ ->
        conn
        |> put_status(:not_found)
        |> put_view(ErrorView)
        |> put_layout(false)
        |> render("404.html",
          message: "There's no retro here. Make sure you have the correct URL!"
        )
        |> halt()
    end
  end

  defp soft_insert_participation_record!(current_user_id, retro_id) do
    %Participation{user_id: current_user_id, retro_id: retro_id}
    |> Participation.changeset()
    |> Repo.insert!(on_conflict: :nothing)
  end

  defp recent_retros_with_action_items_preloaded(current_user_id) do
    action_items_with_assignee =
      from(
        ai in Idea.action_items(),
        preload: [:assignee],
        order_by: [asc: ai.inserted_at]
      )

    subset =
      from(p in Participation,
        where: p.user_id == ^current_user_id,
        order_by: [desc: p.inserted_at],
        limit: 10
      )

    query =
      from(
        r in Retro,
        join: p in subquery(subset),
        on: p.retro_id == r.id,
        preload: [ideas: ^action_items_with_assignee]
      )

    Repo.all(query)
  end
end

lib/remote_retro_web/views/retro_view.ex
defmodule RemoteRetroWeb.RetroView do
  use Phoenix.Template, root: "lib/remote_retro_web/templates", namespace: RemoteRetroWeb
end

web/controllers/retro_controller.ex
defmodule RemoteRetro.RetroController do
  use RemoteRetro.Web, :controller
  alias RemoteRetro.{Retro, Participation, Idea}
  alias Phoenix.Token

  def index(conn, _params) do
    user = get_session(conn, "current_user")

    render conn, "index.html", %{
      current_user: user,
      retros: recent_retros_with_action_items_preloaded(user),
    }
  end

  def show(conn, params) do
    user = get_session(conn, "current_user")

    upsert_participation_record(user, params["id"])
    render conn, "show.html", %{
      user_token: Token.sign(conn, "user", user),
      retro_uuid: params["id"],
      include_js: true,
    }
  end

  def create(conn, _params) do
    user = get_session(conn, "current_user")

    {:ok, retro} =
      %Retro{facilitator_id: user.id}
      |> Retro.changeset
      |> Repo.insert

    redirect conn, to: "/retros/" <> retro.id
  end

  defp upsert_participation_record(user, retro_id) do
    %Participation{user_id: user.id, retro_id: retro_id}
    |> Participation.changeset
    |> Repo.insert_or_update
  end

  defp recent_retros_with_action_items_preloaded(user) do
    action_items_with_assignee =
      from ai in Idea.action_items,
      preload: [:assignee],
      order_by: [asc: ai.inserted_at]

    query =
      from r in assoc(user, :retros),
      limit: 10,
      preload: [ideas: ^action_items_with_assignee],
      order_by: [desc: r.inserted_at]

    Repo.all(query)
  end
end

lib/remote_retro_web/templates/retro/index.html.eex
<script defer="defer" fetchpriority="high" importance="high" src="<%= Routes.static_url(@conn, "/js/jquery.min.js") %>"></script>
<script defer="defer" fetchpriority="high" importance="high" src="<%= Routes.static_url(@conn, "/js/semantic.min.js") %>"></script>

<%= if Enum.count(@retros) == 0 do %>
  <div class="ui centered welcome tiny longer modal">
    <div class="ui center aligned basic very padded segment no-margin-bottom">
      <h2 class="ui header">Welcome, <%= assigns[:current_user].given_name %>!</h2>
      <p>
        You're about to take part in your first RemoteRetro, traversing the following stages:
      </p>
    </div>
    <div class="ui stackable attached vertical steps">
      <div class="step">
        <i class="users icon"></i>
        <div class="content">
          <div class="title">The Lobby</div>
          <div class="description">Gather the team!</div>
        </div>
      </div>
      <div class="step">
        <i class="heart icon"></i>
        <div class="content">
          <div class="title">The Retrospective Prime Directive</div>
          <div class="description">Frame the retro as a safe, collaborative space</div>
        </div>
      </div>
      <div class="step">
        <i class="idea icon"></i>
        <div class="content">
          <div class="title">Idea Generation</div>
          <div class="description">Invite ideas from participants</div>
        </div>
      </div>
      <div class="step grouping">
        <i class="object ungroup outline icon"></i>
        <div class="content">
          <div class="title">Grouping</div>
          <div class="description">Group ideas to identify themes and patterns</div>
        </div>
      </div>
      <div class="step">
        <i class="envelope outline icon"></i>
        <div class="content">
          <div class="title">Labeling + Voting</div>
          <div class="description">Vote anonymously on what to discuss</div>
        </div>
      </div>
      <div class="step">
        <i class="comments icon"></i>
        <div class="content">
          <div class="title">Action Item Generation</div>
          <div class="description">Generate and commit to action items</div>
        </div>
      </div>
      <div class="final step">
        <i class="send icon"></i>
        <div class="content">
          <div class="title">Retrospective Close</div>
          <div class="description">Distribute action items and depart!</div>
        </div>
      </div>
    </div>
    <%= form_for @conn, Routes.retro_path(@conn, :create), [as: :retro, class: "ui form content"], fn _f -> %>
      <button type="submit" class="ui blue right labeled fluid icon button">
        Let's Create Your First Retrospective!
        <i class="arrow right icon"></i>
      </button>
    <% end %>
  </div>

  <script>
    window.addEventListener('DOMContentLoaded', function() {
      $(".longer.modal").modal({
        observeChanges: true,
        closable: false,
        duration: <%= if Application.get_env(:remote_retro, :env) == :test, do: "0", else: "250" %>,
      }).modal("show");

      $(".final.step").on("animationstart", function(){
        $(".ui.form.content").css({ opacity: 1 });
      });
    })
  </script>
<% else %>
  <%= form_for @conn, Routes.retro_path(@conn, :create), [as: :retro, class: "ui tiny modal retro-format-modal"], fn _f -> %>
    <div class="ui center aligned large header">Select format:</div>
    <div class="ui unstackable items scrolling content">
      <input type="radio" class="visually-hidden" id="happy-sad-confused" name="format"  value="Happy/Sad/Confused" checked />
      <label class="item" for="happy-sad-confused">
        <div class="ui tiny image">
          <img src="<%= Routes.static_url(@conn, "/images/happy.svg") %>" />
        </div>
        <div class="content">
          <p class="header">Happy/Sad/Confused</p>
          <div class="meta">
            <span>
              Standard iteration retrospective for teams new to retrospectives. Ideal for unearthing wins, concerns, and painpoints in a collaborative setting where the team can decide the most impactful changes they can make to their process.
            </span>
          </div>
          <div class="extra">
            Suggested time allotment: 1 hour
          </div>
        </div>
      </label>
      <input type="radio" class="visually-hidden" id="start-stop-continue" name="format" value="Start/Stop/Continue" />
      <label class="item" for="start-stop-continue">
        <div class="ui tiny image">
          <img src="<%= Routes.static_url(@conn, "/images/traffic_light.svg") %>" />
        </div>
        <div class="content">
          <p class="header">Start/Stop/Continue</p>
          <div class="meta">
            <span>
              A format focused on the rapid brainstorming of possible action items, and honing the ones most likely to drive positive change in the team.
            </span>
          </div>
          <div class="extra">
            Suggested time allotment: 45 - 60 minutes
          </div>
        </div>
      </label>
    </div>
    <div class="submit-button-wrapper">
      <button type="submit" class="ui blue right labeled fluid icon button">
        Let's do it!
        <i class="arrow right icon"></i>
      </button>
    </div>
  <% end %>
  <div class="ui very padded basic segment">
    <h1 class="ui dividing header">My Retros:</h1>
    <ul class="retros-list">
      <%= for retro <- @retros do %>
        <li>
          <a href="<%= Routes.retro_path @conn, :show, retro %>">
            created <%= Timex.format!(retro.inserted_at, "{relative}", :relative) %>
          </a>
          <%= if Enum.count(retro.ideas) > 0 do %>
            <div class="nested-action-items-list hidden">
              <span onclick="toggleItems(this)" class="action-items-label bold">
                <i class="ui down triangle icon"></i>Action Items
              </span>
              <ul>
                <%# ideas retrieved via association are scoped to action_items %>
                <%= for idea <- retro.ideas do %>
                  <li><%= action_item_to_string(idea) %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>

    <div class="ui hidden divider"></div>
    <button type="submit" class="ui blue right labeled icon initiate-retro-creation button">
      Create a Retrospective!
      <i class="arrow right icon"></i>
    </button>
  </div>

  <script>
    // (IE11) Polyfill for `Element.closest`:
    if (!Element.prototype.matches) {
      Element.prototype.matches = Element.prototype.msMatchesSelector ||
                                  Element.prototype.webkitMatchesSelector;
    }

    if (!Element.prototype.closest) {
      Element.prototype.closest = function(s) {
        var el = this;

        do {
          if (el.matches(s)) return el;
          el = el.parentElement || el.parentNode;
        } while (el !== null && el.nodeType === 1);
        return null;
      };
    }

    function toggleItems(toggleIcon) {
      var nestedActionItemsListEl = toggleIcon.closest(".nested-action-items-list");
      nestedActionItemsListEl.classList.toggle("hidden");
    }

    window.addEventListener('DOMContentLoaded', function() {
      $(".initiate-retro-creation.button").on("click", function() {
        $(".retro-format-modal").modal({
          observeChanges: true,
          closable: true,
        }).modal("show");
      });
    });
  </script>
<% end %>

<%# prefetch retro javascript for faster loading on retro creation :) %>
<link rel="prefetch" href="<%= Routes.static_url(@conn, "/js/dll/dll.vendor.js")%>">
<link rel="prefetch" href="<%= app_js(@conn) %>">

lib/remote_retro_web/templates/retro/index.html.heex
<script defer="defer" fetchpriority="high" importance="high" src={Routes.static_url(@conn, "/js/jquery.min.js")}></script>
<script defer="defer" fetchpriority="high" importance="high" src={Routes.static_url(@conn, "/js/semantic.min.js")}></script>

<%= if Enum.count(@retros) == 0 do %>
  <div class="ui centered welcome tiny longer modal">
    <div class="ui center aligned basic very padded segment no-margin-bottom">
      <h2 class="ui header">Welcome, <%= assigns[:current_user_given_name] %>!</h2>
      <p>
        You're about to take part in your first RemoteRetro, traversing the following stages:
      </p>
    </div>
    <div class="ui stackable attached vertical steps">
      <div class="step">
        <i class="users icon"></i>
        <div class="content">
          <div class="title">The Lobby</div>
          <div class="description">Gather the team!</div>
        </div>
      </div>
      <div class="step">
        <i class="heart icon"></i>
        <div class="content">
          <div class="title">The Retrospective Prime Directive</div>
          <div class="description">Frame the retro as a safe, collaborative space</div>
        </div>
      </div>
      <div class="step">
        <i class="idea icon"></i>
        <div class="content">
          <div class="title">Idea Generation</div>
          <div class="description">Invite ideas from participants</div>
        </div>
      </div>
      <div class="step grouping">
        <i class="object ungroup outline icon"></i>
        <div class="content">
          <div class="title">Grouping</div>
          <div class="description">Group ideas to identify themes and patterns</div>
        </div>
      </div>
      <div class="step">
        <i class="envelope outline icon"></i>
        <div class="content">
          <div class="title">Labeling + Voting</div>
          <div class="description">Vote anonymously on what to discuss</div>
        </div>
      </div>
      <div class="step">
        <i class="comments icon"></i>
        <div class="content">
          <div class="title">Action Item Generation</div>
          <div class="description">Generate and commit to action items</div>
        </div>
      </div>
      <div class="final step">
        <i class="send icon"></i>
        <div class="content">
          <div class="title">Retrospective Close</div>
          <div class="description">Distribute action items and depart!</div>
        </div>
      </div>
    </div>
    <%= form_for @conn, Routes.retro_path(@conn, :create), [as: :retro, class: "ui form content"], fn _f -> %>
      <button type="submit" class="ui blue right labeled fluid icon button">
        Let's Create Your First Retrospective!
        <i class="arrow right icon"></i>
      </button>
    <% end %>
  </div>

  <script>
    window.addEventListener('DOMContentLoaded', function() {
      $(".longer.modal").modal({
        observeChanges: true,
        closable: false,
        duration: <%= if Application.get_env(:remote_retro, :env) == :test, do: "0", else: "250" %>,
      }).modal("show");

      $(".final.step").on("animationstart", function(){
        $(".ui.form.content").css({ opacity: 1 });
      });
    })
  </script>
<% else %>
  <%= form_for @conn, Routes.retro_path(@conn, :create), [as: :retro, class: "ui tiny modal retro-format-modal"], fn _f -> %>
    <div class="ui center aligned large header">Select format:</div>
    <div class="ui unstackable items scrolling content">
      <input type="radio" class="visually-hidden" id="happy-sad-confused" name="format"  value="Happy/Sad/Confused" checked />
      <label class="item" for="happy-sad-confused">
        <div class="ui tiny image">
          <img src={Routes.static_url(@conn, "/images/happy.svg")} />
        </div>
        <div class="content">
          <p class="header">Happy/Sad/Confused</p>
          <div class="meta">
            <span>
              Standard iteration retrospective for teams new to retrospectives. Ideal for unearthing wins, concerns, and painpoints in a collaborative setting where the team can decide the most impactful changes they can make to their process.
            </span>
          </div>
          <div class="extra">
            Suggested time allotment: 1 hour
          </div>
        </div>
      </label>
      <input type="radio" class="visually-hidden" id="start-stop-continue" name="format" value="Start/Stop/Continue" />
      <label class="item" for="start-stop-continue">
        <div class="ui tiny image">
          <img src={Routes.static_url(@conn, "/images/traffic_light.svg")} />
        </div>
        <div class="content">
          <p class="header">Start/Stop/Continue</p>
          <div class="meta">
            <span>
              A format focused on the rapid brainstorming of possible action items, and honing the ones most likely to drive positive change in the team.
            </span>
          </div>
          <div class="extra">
            Suggested time allotment: 45 - 60 minutes
          </div>
        </div>
      </label>
    </div>
    <div class="submit-button-wrapper">
      <button type="submit" class="ui blue right labeled fluid icon button">
        Let's do it!
        <i class="arrow right icon"></i>
      </button>
    </div>
  <% end %>
  <div class="ui very padded basic segment">
    <h1 class="ui dividing header">My Retros:</h1>
    <ul class="retros-list">
      <%= for retro <- @retros do %>
        <li>
          <a href={Routes.retro_path(@conn, :show, retro)}>
            created <%= Timex.format!(retro.inserted_at, "{relative}", :relative) %>
          </a>
          <%= if Enum.count(retro.ideas) > 0 do %>
            <div class="nested-action-items-list hidden">
              <span onclick="toggleItems(this)" class="action-items-label bold">
                <i class="ui down triangle icon"></i>Action Items
              </span>
              <ul>
                <%# ideas retrieved via association are scoped to action_items %>
                <%= for idea <- retro.ideas do %>
                  <li><%= action_item_to_string(idea) %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>

    <div class="ui hidden divider"></div>
    <button type="submit" class="ui blue right labeled icon initiate-retro-creation button">
      Create a Retrospective!
      <i class="arrow right icon"></i>
    </button>
  </div>

  <script>
    // (IE11) Polyfill for `Element.closest`:
    if (!Element.prototype.matches) {
      Element.prototype.matches = Element.prototype.msMatchesSelector ||
                                  Element.prototype.webkitMatchesSelector;
    }

    if (!Element.prototype.closest) {
      Element.prototype.closest = function(s) {
        var el = this;

        do {
          if (el.matches(s)) return el;
          el = el.parentElement || el.parentNode;
        } while (el !== null && el.nodeType === 1);
        return null;
      };
    }

    function toggleItems(toggleIcon) {
      var nestedActionItemsListEl = toggleIcon.closest(".nested-action-items-list");
      nestedActionItemsListEl.classList.toggle("hidden");
    }

    window.addEventListener('DOMContentLoaded', function() {
      $(".initiate-retro-creation.button").on("click", function() {
        $(".retro-format-modal").modal({
          observeChanges: true,
          closable: true,
        }).modal("show");
      });
    });
  </script>
<% end %>

<%# prefetch retro javascript for faster loading on retro creation :) %>
<link rel="prefetch" href={Routes.static_url(@conn, "/js/dll/dll.vendor.js")}>
<link rel="prefetch" href={app_js(@conn)}>

lib/remote_retro_web/templates/retro/show.html.eex
<div class="react-root">
  <div class="ui active large centered text loader">
    Connecting...
  </div>
</div>

lib/remote_retro_web/templates/retro/show.html.heex
<div class="react-root">
  <div class="ui active large centered text loader">
    Connecting...
  </div>
</div>
<link rel="preload" as="image" href={@current_user.picture}/>
<link rel="prefetch" as="font" href={Routes.static_url(@conn, "/css/semantic-ui/themes/default/assets/fonts/outline-icons.woff2")} />